[[redirects]]
  from = "/api/:splat"
  to = "/api/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[build]
  functions = "functions"
[functions]
  node_bundler = "esbuild"